---
- name: If required, check that lxml is installed
  block:
  - name: Get lxml install status
    pip:
      name: lxml
    check_mode: yes
    ignore_errors: yes
    register: lxml_status
    delegate_to: localhost
    changed_when: false

  - debug: var=lxml_status

  - name: check lxml
    set_fact:
      lxml_found: True
    when: lxml_status.stdout | regex_search('lxml==.*')

  - name: Assert that lxml is installed on control node
    assert:
      that: lxml_found is defined and lxml_found
      fail_msg: "The 'lxml' Python module must be installed on the Ansible control node. We recommend that you install manually if you can or use the install_lxml.yaml playbook in the playbook folder"
      success_msg: "lxml is installed"
    delegate_to: localhost
  # - when logger_role_standalone == true, then we are using the logger role stand-alone and
  #   lxml definitly needs to be there.
  # - If it is not set, but the agent_log_level is anything other than "info"
  #   we are also going to use the logger role while deploying other agents.
  when: >
    ( logger_role_standalone is defined and logger_role_standalone) or
    ( agent_log_level is defined and agent_log_level != 'info')
