version: "3.7"

services:
  ########################################################
  ### Frontend
  ########################################################

  acc-frontend:
    container_name: acc-frontend
    hostname: acc-frontend
    restart: on-failure
    image: ${DOMAIN}/acc-frontend:${VERSION}
    expose:
      - 80
    ports:
      - 80:80
    # volumes:
    #   - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - acc-net

  ########################################################
  ### Backend
  ########################################################

  acc-backend:
    container_name: acc-backend
    hostname: acc-backend
    restart: on-failure
    image: ${DOMAIN}/acc-backend:${VERSION}
    environment:
      - MONGODB_CONNECTION=mongodb://acc-mongodb:27017
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./acc-backend-data/ansible/agent-files:/app/ansible/agent-files
      - ~/.ssh/aws-services.cer:/app/.ssh/aws-services.cer
    networks:
      - acc-net

  ########################################################
  ### Databases
  ########################################################

  acc-mongodb:
    image: ${DOMAIN}/acc-mongodb:${VERSION}
    container_name: acc-mongodb
    hostname: acc-mongodb
    restart: on-failure
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - acc-mongo-data:/data/db
    networks:
      - acc-net

networks:
  acc-net:

volumes:
  acc-mongo-data: