---
- hosts: linux
  tasks:
    - name: Include variables for the controller settings
      include_vars: vars/controller.yaml

    - include_role:
        name: dotnetcore
      vars:
        # Define Agent Type and Version
        agent_version: ${agent_version}
        agent_type: ${agent_type}

        # The applicationName
        application_name: "${application_name}" # ONLY required if agent type is not machine or db
        tier_name: "${tier_name}" # ONLY required if agent type is not machine or db

        # Directory permissions for agent. These can be set at host level in the invertory as well
        agent_dir_permission: #defaults to root:root if not specified
          user: "appdynamics" # This user must pre-exist. It is recommended to use the PID owner of your Java app
          group: "appdynamics" # This group must pre-exist
        # # Proxy settings
        # enable_proxy: "true"
        # proxy_host: localhost
        # proxy_port: 9090
        # enable_proxy_authentication: "true"
        # proxy_user: "joe"
        # proxy_password: "12345"
