---
- hosts: ansible-1
  roles:
    - role: java
      vars:
        agent_version: ${agent_version}
        agent_type: ${agent_type}
  pre_tasks:
    - name: Include variables for the controller settings
      include_vars: ../vars/controller.yaml
  tasks:
    - include_role:
        name: instrument_tomcat
      vars:
        application_name: ${application_name}
        tier_name: ${tier_name}
        tomcat_config: ${tomcat_config}
        app_user: root
        # tomcat_service: tomcat8
        restart_app: ${restart_app}
        init_and_validate_agent_variables: true
