---
- hosts: all
  tasks:
    - name: Include variables for the controller settings
      include_vars: vars/controller.yaml

    - include_role:
        name: machine
# ---

# #For Production machines
# - hosts: all
#   tasks:
#     - name: Include variables for the controller settings
#       include_vars: vars/controller.yaml

#     # - name: Include variables for JFrog Artifactory settings
#     #   include_vars: vars/artifactory.yaml

#     - include_role:
#         name: machine

