---
- hosts: all
  tasks:
    - name: Include variables for the controller settings
      include_vars: vars/controller.yaml

    - include_role:
        name: appdynamics.agents.db
      vars:
        install_jre: true # set to false if the target machine already contains a JRE
        agent_version: 20.9.0
        agent_type: db
        db_agent_name: "ProdDBAgent"
        #https://docs.appdynamics.com/display/latest/Database+Agent+Configuration+Properties
        # java_system_properties: "-Dappdynamics.http.proxyHost=10.0.4.2 -Dappdynamics.http.proxyPort=9090" # mind the space between each property
        java_system_properties: ''
