---
- name: Check IIS is present
  include_tasks: check_iis.yml
  when: monitor_all_IIS_apps | bool

- name: Set the unique host id
  include_tasks: set_hostid.yml

- name: Install .NET agent
  include_tasks: dotnet-agent.yml
