- name: Set the unique host id so that machines appear correctly for APM
  win_environment:
    state: present
    level: machine
    name: "APPDYNAMICS_AGENT_UNIQUE_HOST_ID"
    value: "{{ ansible_hostname }}"
