---
galaxy_info:
  author: Israel Ogbole (https://galaxy.ansible.com/iogbole)
  role_name: dotnet
  company: AppDynamics
  description: This role installs and configures the AppDynamics DotNet Agent on Windows OS
  license: Apache2
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2008x64
        - 2008R2
        - 2012
        - 2012R2
        - 2016
        - 2019
  galaxy_tags:
    - apm
    - monitoring
    - appdynamics

dependencies:
 - { role: common }