---

- name: Allow '"{{ appdynamics_user }}"' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ appdynamics_user }}'
    line: '%{{ appdynamics_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'