- block:
    - name: Check jboss path is present
      stat: 
        path: "{{ jboss_config | dirname }}"
      register: p
      failed_when: p.stat.isdir is not defined
  rescue:
    - fail:
        msg: "Please make sure {{ jboss_config | dirname }} is present. Is Jboss installed?"
      tags:
        - skip_ansible_lint
