- name: Add appd instrumentation to jboss
  become: yes
  replace:
    path: "{{ jboss_config }}"
    regexp: '^(?:.*export APPD(?:.|\s)+?\s*)?\s*while\s+true;\s*do\s*(if\s*\[.+LAUNCH_JBOSS_IN_BACKGROUND.+)'
    replace: |-
      export APPDYNAMICS_AGENT_APPLICATION_NAME="{{ application_name }}"
      export APPDYNAMICS_AGENT_TIER_NAME="{{ tier_name }}"
      export APPDYNAMICS_AGENT_NODE_NAME="{{ node_name }}"
      export JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=org.jboss.byteman,com.singularity"
      export JAVA_OPTS="$JAVA_OPTS -javaagent:{{ java_agent_dest_folder_linux }}/javaagent.jar{{ ' -Dappdynamics.http.proxyHost='+proxy_host if enable_proxy else '' }}{{' -Dappdynamics.http.proxyPort='+proxy_port if enable_proxy else ''}}"
      while true;do
      \1
    backup: "{{ backup | bool }}"
  notify: Restart app listener
