---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Check Tomcat is responding
    uri:
      url: http://localhost:8080
      return_content: yes
    register: this
    failed_when: "'Tomcat' not in this.content"