---
galaxy_info:
  author: Louis Nieuwoudt
  description: Apply log4j settings to agent
  role_name: logger
  license:
    - Apache2
  min_ansible_version: 2.9
  platforms:
    - name: Alpine
      verisions:
        - all
    - name: Archlinux
      verisions:
        - all
    - name: Debian
      versions:
        - buster
        - stretch
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 31
        - 32
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - xenial
  galaxy_tags:
    - apm
    - monitoring
    - appdynamics

dependencies:
  - { role: common }
