---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
lint: |
  set -e
  yamllint .
  flake8
  ansible-lint
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    prepare: ${MOLECULE_PLAYBOOK:-prepare.yaml}
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
