---
galaxy_info:
  author: Israel Ogbole (https://galaxy.ansible.com/iogbole)
  role_name: db
  company: AppDynamics
  description: This role installs and configures the AppDynamics Database Agent
  license: Apache2
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
        - xenial
        - artful
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
    - name: EL
      versions:
        - 8
        - 7
        - 6
  galaxy_tags:
    - apm
    - monitoring
    - appdynamics

dependencies:
 - { role: common }
 - { role: linux_pkg, when: ansible_os_family == 'RedHat' or  ansible_os_family == 'Debian'}
 #- { role: win_pkg, when: ansible_os_family == 'Windows' }
 #when: lookup('env', 'MOLECULE_FILE')